name: CI/CD for Auth Service

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t kincirangin/auth-service:latest .

    - name: Push Docker Image to DockerHub
      run: docker push kincirangin/auth-service:latest

  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          docker pull kincirangin/auth-service:latest
          docker stop auth-service || true
          docker rm auth-service || true
          docker run -d --name auth-service --network envoy-proxy -p 50002:50002 --restart always kincirangin/auth-service:latest
          docker image prune -f